/**
 * Right Loading Planner - PDF Report Generator Module
 * Utilizes jsPDF and jsPDF-AutoTable to build professional shipping documents.
 */

class PDFGenerator {
  /**
   * Generates a complete cargo loading and shipment report
   * @param {Object} shipment - Shipment details
   * @param {Array} cargoItems - Cargo item details
   * @param {Object} packingResult - The output of the PackingEngine
   * @param {Object} companyDetails - Settings: Company details (Name, Address, etc.)
   */
  static generateReport(shipment, cargoItems, packingResult, companyDetails = {}) {
    if (typeof window.jspdf === 'undefined') {
      alert('PDF generation library not loaded. Please verify your connection.');
      return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const primaryColor = [25, 161, 150]; // #19A196
    const secondaryColor = [217, 243, 239]; // #D9F3EF
    const darkColor = [44, 62, 80]; // Charcoal

    const companyName = companyDetails.companyName || 'Right Logistics Pvt. Ltd.';
    const companyAddress = companyDetails.companyAddress || '701, Trade Center, Bandra Kurla Complex, Mumbai - 400051, India';
    const companyEmail = companyDetails.companyEmail || 'planning@rightlogistics.com';
    const companyPhone = companyDetails.companyPhone || '+91 22 6789 0000';

    // Page number helper
    const pageCount = doc.internal.getNumberOfPages();
    
    const drawHeader = (pageTitle) => {
      // Draw top header accent line
      doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.rect(0, 0, 210, 8, 'F');

      // Brand Title
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(20);
      doc.text('RIGHT LOGISTICS', 14, 22);

      doc.setFontSize(9);
      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(110, 110, 110);
      doc.text('PLANNING & OPTIMIZATION DIVISION', 14, 26);

      // Company Info (Right aligned)
      doc.setFontSize(9);
      doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
      doc.text(companyName, 196, 18, { align: 'right' });
      doc.setFontSize(8);
      doc.setTextColor(130, 130, 130);
      doc.text(companyAddress, 196, 22, { align: 'right' });
      doc.text(`Email: ${companyEmail} | Phone: ${companyPhone}`, 196, 26, { align: 'right' });

      // Divider line
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.5);
      doc.line(14, 30, 196, 30);

      // Document Name
      doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.rect(14, 35, 182, 10, 'F');

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.text(pageTitle.toUpperCase(), 18, 41.5);
      
      const dateStr = new Date(shipment.date || Date.now()).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
      });
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
      doc.text(`Date: ${dateStr}`, 192, 41.5, { align: 'right' });
    };

    const drawFooter = (pageNum, totalPages) => {
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text('Generated by Right Loading Planner - Secure SaaS Platform', 14, 285);
      doc.text(`Page ${pageNum} of ${totalPages}`, 196, 285, { align: 'right' });
    };

    // ==========================================
    // PAGE 1: SHIPMENT SUMMARY & UTILIZATION
    // ==========================================
    drawHeader('Shipment Optimization Report');

    // Metadata Block
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text('SHIPMENT DETAILS', 14, 55);
    
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);
    doc.text([
      `Shipment ID:  ${shipment.shipmentId || 'N/A'}`,
      `Customer ID:  ${shipment.customerId || 'Walk-in'}`,
      `Status:           ${shipment.status || 'Draft'}`,
      `Notes:            ${shipment.notes || 'None'}`
    ], 14, 60);

    // Calc General Totals
    let totalCbm = 0;
    let totalWeight = 0;
    let totalQty = 0;
    cargoItems.forEach(item => {
      totalCbm += (item.length * item.width * item.height) * item.quantity;
      totalWeight += item.weight * item.quantity;
      totalQty += item.quantity;
    });

    doc.setFont('Helvetica', 'bold');
    doc.text('CARGO METRICS', 110, 55);
    doc.setFont('Helvetica', 'normal');
    doc.text([
      `Total Cargo Volume: ${totalCbm.toFixed(3)} CBM`,
      `Total Cargo Weight: ${totalWeight.toFixed(1)} kg`,
      `Total Items Count:  ${totalQty} units`,
      `Plan Created By:     Operations Desk`
    ], 110, 60);

    // Recommended Container Section
    const containerCount = packingResult.totalContainersRequired || 1;
    const recContainer = packingResult.container?.name || '20GP';
    
    // Grey Card Background for Results
    doc.setFillColor(248, 249, 250);
    doc.rect(14, 82, 182, 38, 'F');
    
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text('OPTIMIZATION ENGINE OUTCOME', 18, 89);
    
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text(`Recommended Plan: ${containerCount} x ${recContainer} Container(s)`, 18, 97);

    // Draw little status boxes
    // Space Utilization Card
    doc.setFillColor(235, 235, 235);
    doc.rect(18, 102, 50, 13, 'F');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text('VOLUME UTILIZATION', 21, 106);
    doc.setFontSize(10);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(`${packingResult.containers?.[0]?.spaceUtilization || 0}%`, 21, 112);

    // Weight Utilization Card
    doc.setFillColor(235, 235, 235);
    doc.rect(72, 102, 50, 13, 'F');
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text('WEIGHT UTILIZATION', 75, 106);
    doc.setFontSize(10);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(`${packingResult.containers?.[0]?.weightUtilization || 0}%`, 75, 112);

    // Loading Efficiency Card
    doc.setFillColor(235, 235, 235);
    doc.rect(126, 102, 50, 13, 'F');
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text('UNPACKED CRITICAL ITEMS', 129, 106);
    doc.setFontSize(10);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(packingResult.unpackedItems?.length > 0 ? [192, 57, 43] : primaryColor);
    doc.text(`${packingResult.unpackedItems?.length || 0} left`, 129, 112);

    // Table of Cargo items Summary
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text('CARGO PACKING LIST DETAILS', 14, 130);

    const cargoTableRows = cargoItems.map((item, index) => [
      index + 1,
      item.name,
      item.type,
      `${item.length} x ${item.width} x ${item.height}`,
      item.weight,
      item.quantity,
      item.stackable === 'Yes' ? 'Yes' : 'No',
      item.tiltable === 'Yes' ? 'Yes' : 'No',
      item.notes || '-'
    ]);

    doc.autoTable({
      startY: 134,
      head: [['#', 'Item Description', 'Cargo Type', 'Dims L x W x H (m)', 'Unit Wt (kg)', 'Qty', 'Stackable', 'Tiltable', 'Notes']],
      body: cargoTableRows,
      theme: 'striped',
      headStyles: { fillColor: primaryColor, textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 1.5 },
      columnStyles: {
        0: { cellWidth: 8 },
        1: { cellWidth: 38 },
        2: { cellWidth: 18 },
        3: { cellWidth: 28 },
        4: { cellWidth: 18 },
        5: { cellWidth: 10 },
        6: { cellWidth: 16 },
        7: { cellWidth: 14 },
        8: { cellWidth: 32 }
      }
    });

    // ==========================================
    // PAGE 2: LOADING SEQUENCING & LAYOUT COORDINATES
    // ==========================================
    doc.addPage();
    drawHeader('Loading Sequencing Plan');

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkColor[0], darkColor[1], darkColor[2]);
    doc.text('STEP-BY-STEP STEPPING SEQUENCE / PLACEMENT MATRIX', 14, 53);
    
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 100, 100);
    doc.text('Operations Guide: Follow the sequence below to load cargo. Positions are measured from the container Floor-Back-Left corner.', 14, 58);

    // Flatten packed items across all containers
    const placementRows = [];
    if (packingResult.containers && packingResult.containers.length > 0) {
      packingResult.containers.forEach((cnt, cntIdx) => {
        cnt.packedItems.forEach((box, boxIdx) => {
          placementRows.push([
            `Container #${cntIdx + 1}`,
            boxIdx + 1,
            box.name,
            box.type,
            `${box.l} x ${box.w} x ${box.h}`,
            box.weight,
            `(${box.x.toFixed(2)}, ${box.y.toFixed(2)}, ${box.z.toFixed(2)})`,
            `L=${box.l.toFixed(2)} / W=${box.w.toFixed(2)} / H=${box.h.toFixed(2)}`
          ]);
        });
      });
    }

    if (placementRows.length === 0) {
      placementRows.push([['No packed items computed. Ensure cargo list is optimization-processed.']]);
    }

    doc.autoTable({
      startY: 62,
      head: [['Target Space', 'Seq #', 'Cargo Description', 'Type', 'Dims Packed (m)', 'Unit Wt', 'Coords (X, Y, Z)', 'Orientation Status']],
      body: placementRows,
      theme: 'grid',
      headStyles: { fillColor: darkColor, textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 1.2 },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 12 },
        2: { cellWidth: 42 },
        3: { cellWidth: 18 },
        4: { cellWidth: 26 },
        5: { cellWidth: 14 },
        6: { cellWidth: 28 },
        7: { cellWidth: 20 }
      }
    });

    // Write leftover items if any
    if (packingResult.unpackedItems && packingResult.unpackedItems.length > 0) {
      const startY = doc.previousAutoTable.finalY + 10;
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(192, 57, 43); // Red Alert
      doc.text('WARNING: UNPACKED CARGO ITEMS (EXCEEDED CONTAINER LIMITS)', 14, startY);

      const unpackedRows = packingResult.unpackedItems.map((item, index) => [
        index + 1,
        item.name,
        item.type,
        `${item.l} x ${item.w} x ${item.h}`,
        item.weight,
        item.notes || '-'
      ]);

      doc.autoTable({
        startY: startY + 4,
        head: [['#', 'Item Description', 'Cargo Type', 'Dims L x W x H (m)', 'Weight (kg)', 'Notes']],
        body: unpackedRows,
        theme: 'striped',
        headStyles: { fillColor: [192, 57, 43], textColor: [255, 255, 255] },
        styles: { fontSize: 8, cellPadding: 1.5 }
      });
    }

    // Add page numbers on all pages
    const totalPages = doc.internal.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      drawFooter(p, totalPages);
    }

    // Save/Download PDF
    const filename = `Right_Logistics_Report_${shipment.shipmentId || 'Export'}.pdf`;
    doc.save(filename);
  }
}

window.PDFGenerator = PDFGenerator;
